Fix il2cpp error (take 2) (#548)
* Revert "Unity il2cpp build fix (#543)"

This reverts commit ba4555ea24d518029a99084921a776b032935252.

* Fix il2cpp error - take 2

Previous commit about this issue reverted since it wasn't fixing the issue. The actual error was:

Error: IL2CPP error for method 'System.Char[] NATS.Client.Core.Internal.NuidWriter::Refresh(System.UInt64&)' in assembly NATS.Client.Core.dll
System.ArgumentOutOfRangeException:
 Cannot create a constant value for types of System.UIntPtr for System.UIntPtr NATS.Client.Core.Internal.NuidWriter::NuidLength (Parameter 'declaredParameterOrFieldType')

 Looking at Unsafe.Add examples passing in uint or int instead of nuint is fine:

 e.g. https://github.com/dotnet/runtime/blob/a7efcd9ca9255dc9faa8b4a2761cdfdb62619610/src/libraries/System.Private.CoreLib/src/System/Buffer.cs#L84

 Note: I had to revert the last two commits (so ignore the previous four commits) to main which was done by mistake without PRs.

* IL2CPP error docs